name: CI

on:
  push:
    branches: [main] # Trigger on push to main branch
  pull_request:
    branches: [main] # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.stats()' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      MONGO_URI: mongodb://localhost:27017
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run test:e2e

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Add your deployment script or commands here
          npm run start:prod
